-- Local Variables --
local v = script.Parent.Monitor
local v1 = script.Parent.Monitor1
local v2 = script.Parent.Monitor2
local v3 = script.Parent.Monitor3
local v4 = script.Parent.Monitor4
local v5 = script.Parent.Monitor5
local term = script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text

-- Functions (This will be what activates when a function is called.) --
function clr()
		script.Parent.Monitor.SurfaceGui.Main.Bank.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.Bank.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.Bank.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.Bank.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.Bank.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.Bank.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor.SurfaceGui.Main.BankChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.BankChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.BankChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.BankChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.BankChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.BankChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor.SurfaceGui.Main.Benham.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.Benham.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.Benham.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.Benham.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.Benham.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.Benham.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor.SurfaceGui.Main.BenhamChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.BenhamChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.BenhamChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.BenhamChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.BenhamChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.BenhamChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor.SurfaceGui.Main.Connsborough.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.Connsborough.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.Connsborough.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.Connsborough.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.Connsborough.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.Connsborough.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor.SurfaceGui.Main.ConnsboroughChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.ConnsboroughChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.ConnsboroughChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.ConnsboroughChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.ConnsboroughChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.ConnsboroughChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor.SurfaceGui.Main.Darkton.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.Darkton.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.Darkton.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.Darkton.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.Darkton.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.Darkton.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor.SurfaceGui.Main.Meadowview.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.Meadowview.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.Meadowview.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.Meadowview.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.Meadowview.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.Meadowview.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor.SurfaceGui.Main.NorthSublandVillages.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.NorthSublandVillages.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.NorthSublandVillages.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.NorthSublandVillages.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.NorthSublandVillages.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.NorthSublandVillages.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor.SurfaceGui.Main.NorthSublandVillagesChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.NorthSublandVillagesChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.NorthSublandVillagesChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.NorthSublandVillagesChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.NorthSublandVillagesChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.NorthSublandVillagesChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor.SurfaceGui.Main.Rosetree.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.Rosetree.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.Rosetree.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.Rosetree.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.Rosetree.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.Rosetree.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor.SurfaceGui.Main.SublandAirport.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.SublandAirport.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.SublandAirport.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.SublandAirport.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.SublandAirport.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.SublandAirport.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor.SurfaceGui.Main.SublandAirportChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.SublandAirportChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.SublandAirportChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.SublandAirportChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.SublandAirportChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.SublandAirportChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor.SurfaceGui.Main.Next.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor1.SurfaceGui.Main.Next.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor2.SurfaceGui.Main.Next.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor3.SurfaceGui.Main.Next.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor4.SurfaceGui.Main.Next.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor5.SurfaceGui.Main.Next.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor.SurfaceGui.Main.TopServiceUpdates.Position = (UDim2.new(0, 0, -1, 15))
		script.Parent.Monitor1.SurfaceGui.Main.TopServiceUpdates.Position = (UDim2.new(0, 0, -1, 15))
		script.Parent.Monitor2.SurfaceGui.Main.TopServiceUpdates.Position = (UDim2.new(0, 0, -1, 15))
		script.Parent.Monitor3.SurfaceGui.Main.TopServiceUpdates.Position = (UDim2.new(0, 0, -1, 15))
		script.Parent.Monitor4.SurfaceGui.Main.TopServiceUpdates.Position = (UDim2.new(0, 0, -1, 15))
		script.Parent.Monitor5.SurfaceGui.Main.TopServiceUpdates.Position = (UDim2.new(0, 0, -1, 15))
		script.Parent.Monitor.SurfaceGui.Main.BottomServiceUpdates.Position = (UDim2.new(0, 0, 1, 15))
		script.Parent.Monitor1.SurfaceGui.Main.BottomServiceUpdates.Position = (UDim2.new(0, 0, 1, 15))
		script.Parent.Monitor2.SurfaceGui.Main.BottomServiceUpdates.Position = (UDim2.new(0, 0, 1, 15))
		script.Parent.Monitor3.SurfaceGui.Main.BottomServiceUpdates.Position = (UDim2.new(0, 0, 1, 15))
		script.Parent.Monitor4.SurfaceGui.Main.BottomServiceUpdates.Position = (UDim2.new(0, 0, 1, 15))
		script.Parent.Monitor5.SurfaceGui.Main.BottomServiceUpdates.Position = (UDim2.new(0, 0, 1, 15))
		script.Parent.Monitor.SurfaceGui.Main.ServiceUpdatesText.Position = (UDim2.new(0, 0, -1, 15))
		script.Parent.Monitor1.SurfaceGui.Main.ServiceUpdatesText.Position = (UDim2.new(0, 0, -1, 15))
		script.Parent.Monitor2.SurfaceGui.Main.ServiceUpdatesText.Position = (UDim2.new(0, 0, -1, 15))
		script.Parent.Monitor3.SurfaceGui.Main.ServiceUpdatesText.Position = (UDim2.new(0, 0, -1, 15))
		script.Parent.Monitor4.SurfaceGui.Main.ServiceUpdatesText.Position = (UDim2.new(0, 0, -1, 15))
		script.Parent.Monitor5.SurfaceGui.Main.ServiceUpdatesText.Position = (UDim2.new(0, 0, -1, 15))
		script.Parent.Monitor.SurfaceGui.Main.Term.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor1.SurfaceGui.Main.Term.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor2.SurfaceGui.Main.Term.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor3.SurfaceGui.Main.Term.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor4.SurfaceGui.Main.Term.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor5.SurfaceGui.Main.Term.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor.SurfaceGui.Main.TermChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.TermChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.TermChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.TermChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.TermChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.TermChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor.SurfaceGui.Main.TopFollowUsOnTwitter.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor1.SurfaceGui.Main.TopFollowUsOnTwitter.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor2.SurfaceGui.Main.TopFollowUsOnTwitter.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor3.SurfaceGui.Main.TopFollowUsOnTwitter.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor4.SurfaceGui.Main.TopFollowUsOnTwitter.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor5.SurfaceGui.Main.TopFollowUsOnTwitter.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor.SurfaceGui.Main.BottomFollowUsOnTwitter.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.BottomFollowUsOnTwitter.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.BottomFollowUsOnTwitter.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.BottomFollowUsOnTwitter.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.BottomFollowUsOnTwitter.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.BottomFollowUsOnTwitter.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor.SurfaceGui.Main.RosetreeNorth.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.RosetreeNorth.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.RosetreeNorth.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.RosetreeNorth.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.RosetreeNorth.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.RosetreeNorth.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor.SurfaceGui.Main.RosetreeNorthChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.RosetreeNorthChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.RosetreeNorthChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.RosetreeNorthChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.RosetreeNorthChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.RosetreeNorthChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor.SurfaceGui.Main.MarieBeach.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.MarieBeach.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.MarieBeach.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.MarieBeach.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.MarieBeach.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.MarieBeach.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor.SurfaceGui.Main.MarieBeachChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.MarieBeachChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.MarieBeachChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.MarieBeachChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.MarieBeachChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.MarieBeachChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor.SurfaceGui.Main.NotStopping.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor1.SurfaceGui.Main.NotStopping.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor2.SurfaceGui.Main.NotStopping.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor3.SurfaceGui.Main.NotStopping.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor4.SurfaceGui.Main.NotStopping.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor5.SurfaceGui.Main.NotStopping.Position = (UDim2.new(0, 150, -1, 50))
		script.Parent.Monitor.SurfaceGui.Main.NotStoppingAtRosetree.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.NotStoppingAtRosetree.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.NotStoppingAtRosetree.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.NotStoppingAtRosetree.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.NotStoppingAtRosetree.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.NotStoppingAtRosetree.Position = (UDim2.new(0, 0, -1, 30))
		script.Parent.Monitor.SurfaceGui.Main.NotStoppingAtRosetreeChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor1.SurfaceGui.Main.NotStoppingAtRosetreeChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor2.SurfaceGui.Main.NotStoppingAtRosetreeChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor3.SurfaceGui.Main.NotStoppingAtRosetreeChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor4.SurfaceGui.Main.NotStoppingAtRosetreeChange.Position = (UDim2.new(0, 0, 1, 30))
		script.Parent.Monitor5.SurfaceGui.Main.NotStoppingAtRosetreeChange.Position = (UDim2.new(0, 0, 1, 30))

end
function BankNext()
	clr()
	wait(2)
	script.Parent.Dependencies.Chm:Play()
	wait(3.238)
	script.Parent.Dependencies.AELServiceTo:Play()
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	wait(2.637)
	if script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - L" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - X" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Bank" then
		script.Parent.Dependencies.Bank:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Meadowview" then
		script.Parent.Dependencies.Meadowview:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - L" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - X" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "North Subland Villages" then
		script.Parent.Dependencies.NSublandVillages:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Connsborough" then
		script.Parent.Dependencies.Connsborough:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree North" then
		script.Parent.Dependencies.RosetreeNorth:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Marie Beach" then
		script.Parent.Dependencies.MarieBeach:Play()
	end
	wait(1.6)
	script.Parent.Dependencies.NextStation:Play()
	wait(2.37)
	script.Parent.Dependencies.Bank:Play()
	v.SurfaceGui.Main.Bank:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Bank:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Bank:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Bank:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Bank:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Bank:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(0.757)
	script.Parent.Dependencies.DoorRight:Play()
	wait(3.004)
	script.Parent.Dependencies.SM:Play()
	v.SurfaceGui.Main.BankChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.BankChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.BankChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.BankChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.BankChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.BankChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(3.918)
	script.Parent.Dependencies.DoorsWillOpenAutomatically:Play()
	wait(3.55)
	script.Parent.Dependencies.BrenAnnouncement:Play()
	script.Parent.Monitor.Value.Value = -1
	wait(7)
	v.SurfaceGui.Main.BankChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v1.SurfaceGui.Main.BankChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v2.SurfaceGui.Main.BankChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v3.SurfaceGui.Main.BankChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v4.SurfaceGui.Main.BankChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v5.SurfaceGui.Main.BankChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	wait(2)		
	v.SurfaceGui.Main.Bank:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Bank:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Bank:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Bank:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Bank:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Bank:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	wait(1.5)
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
end
function ConnsboroughNext()
	clr()
	wait(2)
	script.Parent.Dependencies.Chm:Play()
	wait(3.238)
	script.Parent.Dependencies.AELServiceTo:Play()
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	wait(2.637)
	if script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - L" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - X" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Bank" then
		script.Parent.Dependencies.Bank:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Meadowview" then
		script.Parent.Dependencies.Meadowview:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - L" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - X" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "North Subland Villages" then
		script.Parent.Dependencies.NSublandVillages:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Connsborough" then
		script.Parent.Dependencies.Connsborough:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree North" then
		script.Parent.Dependencies.RosetreeNorth:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Marie Beach" then
		script.Parent.Dependencies.MarieBeach:Play()
	end
	wait(1.6)
	script.Parent.Dependencies.NextStation:Play()
	wait(2.37)
	script.Parent.Dependencies.Connsborough:Play()
	v.SurfaceGui.Main.Connsborough:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Connsborough:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Connsborough:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Connsborough:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Connsborough:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Connsborough:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(1.358)
	script.Parent.Dependencies.DoorLeft:Play()
	wait(2.821)
	script.Parent.Dependencies.SM:Play()
	v.SurfaceGui.Main.ConnsboroughChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.ConnsboroughChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.ConnsboroughChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.ConnsboroughChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.ConnsboroughChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.ConnsboroughChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(3.918)
	script.Parent.Dependencies.DoorsWillOpenAutomatically:Play()
	wait(3.943)
	script.Parent.Dependencies.BrenAnnouncement:Play()
	wait(5.43)
	script.Parent.Monitor.Value.Value = -1
	wait(7)
	v.SurfaceGui.Main.ConnsboroughChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v1.SurfaceGui.Main.ConnsboroughChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v2.SurfaceGui.Main.ConnsboroughChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v3.SurfaceGui.Main.ConnsboroughChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v4.SurfaceGui.Main.ConnsboroughChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v5.SurfaceGui.Main.ConnsboroughChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	wait(2)
	v.SurfaceGui.Main.Connsborough:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Connsborough:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Connsborough:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Connsborough:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Connsborough:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Connsborough:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	wait(1.5)
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
end
function DarktonNext()
	clr()
	wait(2)
	script.Parent.Dependencies.Chm:Play()
	wait(3.238)
	script.Parent.Dependencies.AELServiceTo:Play()
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	wait(2.637)
	if script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - L" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - X" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Bank" then
		script.Parent.Dependencies.Bank:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Meadowview" then
		script.Parent.Dependencies.Meadowview:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - L" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - X" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "North Subland Villages" then
		script.Parent.Dependencies.NSublandVillages:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Connsborough" then
		script.Parent.Dependencies.Connsborough:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree North" then
		script.Parent.Dependencies.RosetreeNorth:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Marie Beach" then
		script.Parent.Dependencies.MarieBeach:Play()
	end
	wait(1.6)
	script.Parent.Dependencies.NextStation:Play()
	wait(2.25)
	script.Parent.Dependencies.Darkton:Play()
	v.SurfaceGui.Main.Darkton:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Darkton:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Darkton:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Darkton:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Darkton:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Darkton:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(1.38)
	script.Parent.Dependencies.DoorRight:Play()
	wait(3)
	v.SurfaceGui.Main.DarktonChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.DarktonChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.DarktonChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.DarktonChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.DarktonChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.DarktonChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	script.Parent.Monitor.Value.Value = -1
	wait(5)
	v.SurfaceGui.Main.DarktonChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v1.SurfaceGui.Main.DarktonChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v2.SurfaceGui.Main.DarktonChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v3.SurfaceGui.Main.DarktonChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v4.SurfaceGui.Main.DarktonChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v5.SurfaceGui.Main.DarktonChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	wait(2)
	v.SurfaceGui.Main.Darkton:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Darkton:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Darkton:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Darkton:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Darkton:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Darkton:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	wait(1.5)
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
end
function MeadowviewNext()
	--
end
function NSublandVillagesNext()
	clr()
	wait(2)
	script.Parent.Dependencies.Chm:Play()
	wait(3.238)
	script.Parent.Dependencies.AELServiceTo:Play()
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)	
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	wait(2.637)
	if script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - L" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - X" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Bank" then
		script.Parent.Dependencies.Bank:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Meadowview" then
		script.Parent.Dependencies.Meadowview:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - L" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - X" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "North Subland Villages" then
		script.Parent.Dependencies.NSublandVillages:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Connsborough" then
		script.Parent.Dependencies.Connsborough:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree North" then
		script.Parent.Dependencies.RosetreeNorth:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Marie Beach" then
		script.Parent.Dependencies.MarieBeach:Play()
	end
	wait(1.6)
	script.Parent.Dependencies.NextStation:Play()
	wait(2.25)
	script.Parent.Dependencies.NSublandVillages:Play()
	v.SurfaceGui.Main.NorthSublandVillages:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.NorthSublandVillages:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.NorthSublandVillages:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.NorthSublandVillages:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.NorthSublandVillages:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.NorthSublandVillages:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(2.01)
	if script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "North Subland Villages" then
	script.Parent.Dependencies.DoorRight:Play()
	else
	script.Parent.Dependencies.DoorLeft:Play()
	wait(3)
	script.Parent.Dependencies.ChangeGandN:Play()
	v.SurfaceGui.Main.NorthSublandVillagesChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.NorthSublandVillagesChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.NorthSublandVillagesChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.NorthSublandVillagesChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.NorthSublandVillagesChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.NorthSublandVillagesChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	script.Parent.Monitor.Value.Value = -1
	wait(7)
	v.SurfaceGui.Main.NorthSublandVillagesChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v1.SurfaceGui.Main.NorthSublandVillagesChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v2.SurfaceGui.Main.NorthSublandVillagesChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v3.SurfaceGui.Main.NorthSublandVillagesChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v4.SurfaceGui.Main.NorthSublandVillagesChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v5.SurfaceGui.Main.NorthSublandVillagesChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	wait(2)
	v.SurfaceGui.Main.NorthSublandVillages:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.NorthSublandVillages:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.NorthSublandVillages:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.NorthSublandVillages:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.NorthSublandVillages:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.NorthSublandVillages:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	wait(1.5)
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	end
	end
function RosetreeNext()
	clr()
	wait(2)
	script.Parent.Dependencies.Chm:Play()
	wait(3.238)
	script.Parent.Dependencies.AELServiceTo:Play()
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	wait(2.637)
	if script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - L" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - X" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Bank" then
		script.Parent.Dependencies.Bank:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Meadowview" then
		script.Parent.Dependencies.Meadowview:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - L" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - X" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "North Subland Villages" then
		script.Parent.Dependencies.NSublandVillages:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Connsborough" then
		script.Parent.Dependencies.Connsborough:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree North" then
		script.Parent.Dependencies.RosetreeNorth:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Marie Beach" then
		script.Parent.Dependencies.MarieBeach:Play()
	end
	wait(1.6)
	script.Parent.Dependencies.NextStation:Play()
	wait(2.30)
	script.Parent.Dependencies.Rosetree:Play()
	v.SurfaceGui.Main.Rosetree:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Rosetree:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Rosetree:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Rosetree:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Rosetree:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Rosetree:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(1.130)
	script.Parent.Dependencies.DoorLeft:Play()
	wait(3)
	script.Parent.Dependencies.SM:Play()
	v.SurfaceGui.Main.RosetreeChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.RosetreeChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.RosetreeChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.RosetreeChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.RosetreeChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.RosetreeChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(3.91)
	script.Parent.Dependencies.DoorsWillOpenAutomatically:Play()
	wait(3.7)
	script.Parent.Monitor.Value.Value = -1
	wait(7)
	v.SurfaceGui.Main.RosetreeChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v1.SurfaceGui.Main.RosetreeChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v2.SurfaceGui.Main.RosetreeChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v3.SurfaceGui.Main.RosetreeChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v4.SurfaceGui.Main.RosetreeChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v5.SurfaceGui.Main.RosetreeChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	wait(2)
	v.SurfaceGui.Main.Rosetree:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Rosetree:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Rosetree:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Rosetree:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Rosetree:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Rosetree:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	wait(1.5)
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
end
function SublandAirportNext()
	clr()
	wait(2)
	script.Parent.Dependencies.Chm:Play()
	wait(3.238)
	script.Parent.Dependencies.AELServiceTo:Play()
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	wait(2.637)
	if script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - L" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - X" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Bank" then
		script.Parent.Dependencies.Bank:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Meadowview" then
		script.Parent.Dependencies.Meadowview:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - L" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - X" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "North Subland Villages" then
		script.Parent.Dependencies.NSublandVillages:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Connsborough" then
		script.Parent.Dependencies.Connsborough:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree North" then
		script.Parent.Dependencies.RosetreeNorth:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Marie Beach" then
		script.Parent.Dependencies.MarieBeach:Play()
	end
	wait(1.6)
	script.Parent.Dependencies.NextStation:Play()
	wait(2.30)
	script.Parent.Dependencies.SublandAirport:Play()
	v.SurfaceGui.Main.SublandAirport:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.SublandAirport:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.SublandAirport:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.SublandAirport:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.SublandAirport:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.SublandAirport:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(1.59)
	if script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - L" then
		script.Parent.Dependencies.DoorRight:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - X" then
		script.Parent.Dependencies.DoorRight:Play()
	else
		script.Parent.Dependencies.DoorLeft:Play()
	wait(3.004)
	script.Parent.Dependencies.SM:Play()
	v.SurfaceGui.Main.SublandAirportChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.SublandAirportChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.SublandAirportChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.SublandAirportChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.SublandAirportChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.SublandAirportChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(3.918)
	script.Parent.Dependencies.DoorsWillOpenAutomatically:Play()
	script.Parent.Monitor.Value.Value = -1
	wait(7)
	v.SurfaceGui.Main.SublandAirportChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v1.SurfaceGui.Main.SublandAirportChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v2.SurfaceGui.Main.SublandAirportChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v3.SurfaceGui.Main.SublandAirportChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v4.SurfaceGui.Main.SublandAirportChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v5.SurfaceGui.Main.SublandAirportChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	wait(2)
	v.SurfaceGui.Main.SublandAirport:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.SublandAirport:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.SublandAirport:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.SublandAirport:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.SublandAirport:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.SublandAirport:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	wait(1.5)
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	end
	end
function TerminatesHere()
	clr()
	wait(2)
	script.Parent.Dependencies.Chm:Play()
	wait(3.238)
	script.Parent.Dependencies.AELTerminating:Play()
	v.SurfaceGui.Main.Term:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)	
	v1.SurfaceGui.Main.Term:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)	
	v2.SurfaceGui.Main.Term:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)	
	v3.SurfaceGui.Main.Term:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)	
	v4.SurfaceGui.Main.Term:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)	
	v5.SurfaceGui.Main.Term:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v.SurfaceGui.Main.TermChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)	
	v1.SurfaceGui.Main.TermChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)	
	v2.SurfaceGui.Main.TermChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)	
	v3.SurfaceGui.Main.TermChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)	
	v4.SurfaceGui.Main.TermChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)	
	v5.SurfaceGui.Main.TermChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	script.Parent.Monitor.Value.Value = -1
	wait(11.51)
	script.Parent.Dependencies.TYforTravelling:Play()
end
function GreenHillNext()
	
end
function LowerSublandNext()
	
end
function RosetreeNorthNext()
	clr()
	wait(2)
	script.Parent.Dependencies.Chm:Play()
	wait(3.238)
	script.Parent.Dependencies.AELServiceTo:Play()
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	wait(2.637)
	if script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - L" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - X" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Bank" then
		script.Parent.Dependencies.Bank:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Meadowview" then
		script.Parent.Dependencies.Meadowview:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - L" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - X" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "North Subland Villages" then
		script.Parent.Dependencies.NSublandVillages:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Connsborough" then
		script.Parent.Dependencies.Connsborough:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree North" then
		script.Parent.Dependencies.RosetreeNorth:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Marie Beach" then
		script.Parent.Dependencies.MarieBeach:Play()
	end
	wait(1.6)
	script.Parent.Dependencies.NextStation:Play()
	wait(2.37)
	script.Parent.Dependencies.RosetreeNorth:Play()
	v.SurfaceGui.Main.RosetreeNorth:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.RosetreeNorth:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.RosetreeNorth:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.RosetreeNorth:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.RosetreeNorth:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.RosetreeNorth:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(1.149)
	script.Parent.Dependencies.DoorLeft:Play()
	wait(2.821)
	script.Parent.Dependencies.SM:Play()
	v.SurfaceGui.Main.RosetreeNorthChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.RosetreeNorthChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.RosetreeNorthChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.RosetreeNorthChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.RosetreeNorthChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.RosetreeNorthChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(3.918)
	script.Parent.Dependencies.DoorsWillOpenAutomatically:Play()
	wait(3.55)
	script.Parent.Dependencies.BrenAnnouncement:Play()
	script.Parent.Monitor.Value.Value = -1
	wait(7)
	v.SurfaceGui.Main.RosetreeNorthChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v1.SurfaceGui.Main.RosetreeNorthChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v2.SurfaceGui.Main.RosetreeNorthChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v3.SurfaceGui.Main.RosetreeNorthChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v4.SurfaceGui.Main.RosetreeNorthChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v5.SurfaceGui.Main.RosetreeNorthChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	wait(2)		
	v.SurfaceGui.Main.RosetreeNorth:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.RosetreeNorth:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.RosetreeNorth:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.RosetreeNorth:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.RosetreeNorth:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.RosetreeNorth:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	wait(1.5)
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
end
function MarieBeachNext()
	clr()
	wait(2)
	script.Parent.Dependencies.Chm:Play()
	wait(3.238)
	script.Parent.Dependencies.AELServiceTo:Play()
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	wait(2.637)
	if script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - L" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Subland Airport - X" then
		script.Parent.Dependencies.SublandAirport:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Bank" then
		script.Parent.Dependencies.Bank:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Meadowview" then
		script.Parent.Dependencies.Meadowview:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - L" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree - X" then
		script.Parent.Dependencies.Rosetree:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "North Subland Villages" then
		script.Parent.Dependencies.NSublandVillages:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Connsborough" then
		script.Parent.Dependencies.Connsborough:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Rosetree North" then
		script.Parent.Dependencies.RosetreeNorth:Play()
	elseif script.Parent.Monitor.SurfaceGui.Main.Destination.Place1.Text == "Marie Beach" then
		script.Parent.Dependencies.MarieBeach:Play()
	end
	wait(1.6)
	script.Parent.Dependencies.NextStation:Play()
	wait(2.37)
	script.Parent.Dependencies.MarieBeach:Play()
	v.SurfaceGui.Main.MarieBeach:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.MarieBeach:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.MarieBeach:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.MarieBeach:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.MarieBeach:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.MarieBeach:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(1.149)
	script.Parent.Dependencies.DoorLeft:Play()
	wait(2.821)
	v.SurfaceGui.Main.MarieBeachChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.MarieBeachChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.MarieBeachChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.MarieBeachChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.MarieBeachChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.MarieBeachChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(3.918)
	script.Parent.Dependencies.DoorsWillOpenAutomatically:Play()
	wait(3.55)
	script.Parent.Dependencies.BrenAnnouncement:Play()
	script.Parent.Monitor.Value.Value = -1
	wait(7)
	v.SurfaceGui.Main.MarieBeachChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v1.SurfaceGui.Main.MarieBeachChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v2.SurfaceGui.Main.MarieBeachChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v3.SurfaceGui.Main.MarieBeachChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v4.SurfaceGui.Main.MarieBeachChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	v5.SurfaceGui.Main.MarieBeachChange:TweenPosition(UDim2.new(0, 0, 2, 30), "In", "Quart", 1.7)
	wait(2)		
	v.SurfaceGui.Main.MarieBeach:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.MarieBeach:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.MarieBeach:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.MarieBeach:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.MarieBeach:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.MarieBeach:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	wait(1.5)
	v.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.Next:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
end
function NotStoppingAtRosetree()
	clr()
	wait(2)
	script.Parent.Dependencies.Chm:Play()
	wait(3.238)
	script.Parent.Dependencies.NotStoppingAtRosetree:Play()
	script.Parent.Monitor.Value.Value = -1
	v.SurfaceGui.Main.NotStopping:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.NotStopping:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.NotStopping:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.NotStopping:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.NotStopping:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.NotStopping:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	wait(1.7)
	v.SurfaceGui.Main.NotStoppingAtRosetree:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.NotStoppingAtRosetree:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.NotStoppingAtRosetree:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.NotStoppingAtRosetree:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.NotStoppingAtRosetree:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.NotStoppingAtRosetree:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v.SurfaceGui.Main.NotStoppingAtRosetreeChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.NotStoppingAtRosetreeChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.NotStoppingAtRosetreeChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.NotStoppingAtRosetreeChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.NotStoppingAtRosetreeChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.NotStoppingAtRosetreeChange:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	wait(7)
	v.SurfaceGui.Main.NotStoppingAtRosetreeChange:TweenPosition(UDim2.new(0, 0, 1, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.NotStoppingAtRosetreeChange:TweenPosition(UDim2.new(0, 0, 1, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.NotStoppingAtRosetreeChange:TweenPosition(UDim2.new(0, 0, 1, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.NotStoppingAtRosetreeChange:TweenPosition(UDim2.new(0, 0, 1, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.NotStoppingAtRosetreeChange:TweenPosition(UDim2.new(0, 0, 1, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.NotStoppingAtRosetreeChange:TweenPosition(UDim2.new(0, 0, 1, 30), "Out", "Quart", 1.7)
	wait(1.7)
	v.SurfaceGui.Main.NotStoppingAtRosetree:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.NotStoppingAtRosetree:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.NotStoppingAtRosetree:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.NotStoppingAtRosetree:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.NotStoppingAtRosetree:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.NotStoppingAtRosetree:TweenPosition(UDim2.new(0, 0, -1, 30), "Out", "Quart", 1.7)
	wait(1.7)
	v.SurfaceGui.Main.NotStopping:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.NotStopping:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.NotStopping:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.NotStopping:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.NotStopping:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.NotStopping:TweenPosition(UDim2.new(0, 150, -1, 50), "Out", "Quart", 1.7)
end
function ServiceStatus()
	clr()
	wait(0.01)
	v.SurfaceGui.Main.ServiceUpdatesText:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.ServiceUpdatesText:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.ServiceUpdatesText:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.ServiceUpdatesText:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.ServiceUpdatesText:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.ServiceUpdatesText:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	wait(1)
	v.SurfaceGui.Main.TopServiceUpdates:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.TopServiceUpdates:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.TopServiceUpdates:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.TopServiceUpdates:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.TopServiceUpdates:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.TopServiceUpdates:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v.SurfaceGui.Main.BottomServiceUpdates:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.BottomServiceUpdates:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.BottomServiceUpdates:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.BottomServiceUpdates:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.BottomServiceUpdates:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.BottomServiceUpdates:TweenPosition(UDim2.new(0, 0, 0, 15), "Out", "Quart", 1.7)
	script.Parent.Monitor.Value.Value = -1
end
function FollowUs()
	clr()
	wait(0.01)
	v.SurfaceGui.Main.TopFollowUsOnTwitter:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.TopFollowUsOnTwitter:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.TopFollowUsOnTwitter:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.TopFollowUsOnTwitter:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.TopFollowUsOnTwitter:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.TopFollowUsOnTwitter:TweenPosition(UDim2.new(0, 150, 0, 50), "Out", "Quart", 1.7)
	wait(1.4)
	v.SurfaceGui.Main.BottomFollowUsOnTwitter:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v1.SurfaceGui.Main.BottomFollowUsOnTwitter:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v2.SurfaceGui.Main.BottomFollowUsOnTwitter:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v3.SurfaceGui.Main.BottomFollowUsOnTwitter:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v4.SurfaceGui.Main.BottomFollowUsOnTwitter:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	v5.SurfaceGui.Main.BottomFollowUsOnTwitter:TweenPosition(UDim2.new(0, 0, 0, 30), "Out", "Quart", 1.7)
	script.Parent.Monitor.Value.Value = -1
end
-- Functions end --

-- Function callers --
while true do
	wait(0.01)	
	if script.Parent.Monitor.Value.Value == 0 then
		script.Parent.ThisIsValue.Value = 0
		BankNext()
	elseif script.Parent.Monitor.Value.Value == 1 then
		script.Parent.ThisIsValue.Value = 1
		ConnsboroughNext()
	elseif script.Parent.Monitor.Value.Value == 2 then
		script.Parent.ThisIsValue.Value = 2
		DarktonNext()
	elseif script.Parent.Monitor.Value.Value == 3 then
		script.Parent.ThisIsValue.Value = 3
		MeadowviewNext()
	elseif script.Parent.Monitor.Value.Value == 4 then
		script.Parent.ThisIsValue.Value = 4
		NSublandVillagesNext()
	elseif script.Parent.Monitor.Value.Value == 5 then
		script.Parent.ThisIsValue.Value = 5
		RosetreeNext()
	elseif script.Parent.Monitor.Value.Value == 6 then
		script.Parent.ThisIsValue.Value = 6
		SublandAirportNext()
	elseif script.Parent.Monitor.Value.Value == 7 then
		script.Parent.ThisIsValue.Value = 7
		GreenHillNext()
	elseif script.Parent.Monitor.Value.Value == 8 then
		script.Parent.ThisIsValue.Value = 8
		LowerSublandNext()
	elseif script.Parent.Monitor.Value.Value == 10 then
		TerminatesHere()
	elseif script.Parent.Monitor.Value.Value == 11 then
		script.Parent.ThisIsValue.Value = 11
		RosetreeNorthNext()
	elseif script.Parent.Monitor.Value.Value == 12 then
		script.Parent.ThisIsValue.Value = 12
		MarieBeachNext()
	elseif script.Parent.Monitor.Value.Value == 16 then
		--I've managed to fix GetSync issues with the TrelloAPI meaning that ServiceStatus now works!.		
		FollowUs()
	elseif script.Parent.Monitor.Value.Value == 95 then
		NotStoppingAtRosetree()
	elseif script.Parent.Monitor.Value.Value == -2 then
		clr()
end
end